### ISSUE TITLE
Widen chat bot bubble to minimize scrolling

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#16]
Been getting some feedback that scrolling is particularly odious to do in the bot.

Can we widen the chat bot bubble and delete the (freshly optimised) robot icon?

![image](https://user-images.githubusercontent.com/20632432/59483453-cdd22380-8eb0-11e9-8791-33d9fca1942e.png)

**Comment by sitrobotsit** [comment]
What about this (see mockup);

- it's 90% max width instead of 80%. 
- chatbot icon is moved to the top bar
- 2 tone top bar changed to single colour 
- top and bottom paragraph padding changed to .4em instead of 1em
- removal of author element "neauterbot-dev"
- send message icon and expand chat window icon lightened to not pull so much visual focus 

![bot mockup](https://user-images.githubusercontent.com/856535/59501017-eb948e00-8e9a-11e9-9991-e2862c3417ac.png)

**Comment by nicholasamiller** [comment]
It looks much better now.   Are there some extra few pixels to be gained by removing the grey padding around the control?

**Comment by sitrobotsit** [comment]
These styling changes are included in the issue/7 merge request.
