### ISSUE TITLE
Add polyfills for IE11

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#20]
I probably forgot to mention we need to support IE11.

I tested the Telerik control and va-include script work in IE11, so I'm guessing it's just a bundling config issue.

https://nginx-dva-feature-chatbot.govcms.amazee.io/

![image](https://user-images.githubusercontent.com/20632432/60228786-310f7d00-98d7-11e9-89f4-7e4e403a9f93.png)

**Comment by sitrobotsit** [comment]
I've added the [whatwg-fetch ](https://www.npmjs.com/package/whatwg-fetch) pollyfill and it appears to work now. 

Need to run `npm i` again :-)

FYI, I'd be surprised if it ever worked in IE or older versions of Firefox as `window.fetch('https://neuterbot-client-dev.azurewebsites.net/api/directlineToken', { method: 'POST' })` has been in the app without a pollyfill since day one.
