### ISSUE TITLE
Styling CSS optmisations

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#3]
Styles are currently in va-include.css.

**Comment by nicholasamiller** [comment]
Also some styles here: http://dvanewlegacy.prod.acquia-sites.com/sites/all/themes/govkit/css/partials/_chatbot.scss

**Comment by sitrobotsit** [comment]
And there are also inline styles in iframeSource.html and 3 css files from kendo;
kendo.common-office365.min.css
kendo.office365.min.css
kendo.office365.mobile.min.css

Can the http://dvanewlegacy.prod.acquia-sites.com/sites/all/themes/govkit/css/partials/_chatbot.scss file be removed so that all styles for the bot are contained in this repo? 

And then, are you happy for me to make (probably a gulp) task in this repo to build all the scss and css files in to one minified css file so we save http requests?

**Comment by nicholasamiller** [comment]
This sounds like a good plan.  You can copy the scss from that dvanewlegacy domain.
Note I do foresee we will want to make some changes to those kendo css files, or sub in different ones - shouldn't be a problem to just change the bundled files and rebundle.

**Comment by sitrobotsit** [comment]
I did this as part of the magnification and build process. These kendo css files are massive (400kb combined and minified). And I doubt more than 10% of these styles are being used. Not sure how much of a priority performance is but if there's appetite to improve this, then I can look at rewriting these styles. Or maybe asking Kendo what they suggest.

**Comment by nicholasamiller** [comment]
I reckon it is worth it to shed the unused styles somehow.  Telerik has some documentation on how to build up a stylesheet: [https://docs.telerik.com/kendo-ui/styles-and-layout/sass-themes](https://docs.telerik.com/kendo-ui/styles-and-layout/sass-themes).
However, there does not appear to be any automatic bundler.

**Comment by sitrobotsit** [comment]
Using the bare minimum sass files from Telerik via npm, I managed to get the minified css file down to 218kb (from 438kb) and remove all the unused image and font assets (about another 400kb). I still think this is too big but other than rewriting all the sass, I think this is as good as it's going to get. 

The extent of the testing I've done on this is doing a visual compare against the old version in Chrome and Safari at different screen resolutions with a few test phrases e.g. book a taxi, contact the dva. 

This is now merged in to master.  Please run `npm i` to get the Telerik npm package.
