### ISSUE TITLE
Load iframe contents when bot activated

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#8]
Currently the iframe contents load when the host page loads.
The problem with this is that the directline token can expire.
Edit: I'm not actually sure ^^ this is right.  
Need to test to see if the token expires, and this is the cause of a 'failed to connect' error that appears sometimes.

**Comment by sitrobotsit** [comment]
I had a go at a) moving the API token call in to the va-include.js file (which has a few watchers for bot clicks). b) getting va-include.js to call an API call function in the iframeSource.html file. 
Both of these approaches have problems. (b) is probably easiest to get working, but there are CORS problems with this and to get around it, the files would need to be hosted on the same server (not just run from the file system). This is reasonably trivial, but it is a bit of an overhead. 

One thing to consider is that the initialisation of the bot does take a few seconds (due to the speed of the API), so if we move the API call to onclick, the perceived speed is going to be slower. 

Let me know if you'd like me to do anything with this.
